import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { io, Socket } from "socket.io-client";
import axios from 'axios';
import { ClientToServerEvents, ServerToClientEvents, SocketClientType } from '..';
import { useState } from 'react';
import dynamic from 'next/dynamic';
// const Text = dynamic(import('../components/text'), {ssr:false})
import Text from '../components/text'
import Link from 'next/link';

const socket = io(`${process.env.NEXT_PUBLIC_DEV_WS_URL}`)

export type HomeProps = {
  socket: SocketClientType,
};

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Text socket={socket} />
        <Link href={`${process.env.NEXT_PUBLIC_SERVER_API_URL}/api/auth/oauth2/google/logout`}>
        <a>
         Signout
        </a>
       </Link>
      </main>
    </div>
  )
}


export default Home
