import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Login: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <Link href={`${process.env.NEXT_PUBLIC_SERVER_API_URL}/api/auth/oauth2/google`}>
        <a>
         Signin wth Google
        </a>
       </Link>
      </main>
    </div>
  )
}


export default Login
