import axios from 'axios'
import type { NextPage } from 'next'
import { signIn, signOut, useSession } from 'next-auth/react'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Login: NextPage = () => {

  const {data:session} = useSession();
  const onClick = async () => {
    signOut()
  }
  const handler = async () => {
    const {data} = await axios.post('/api/user', {profile:session?.user})
    console.log(data)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {!session ? (
          <button onClick={() => signIn()}>
          Signin wth Google
         </button>
        ): (
          <>
          <p>{session.user?.name}</p>
            <button onClick={onClick}>
              SignOut
            </button>
            <button onClick={handler}>
              Add User
            </button>
          </>
        )}
      </main>
    </div>
  )
}


export default Login
